// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiQ3G8cmHV2tVPMNCqNuMtS2Y3JMgW_4',
    appId: '1:349316653976:web:df448552567c87422641ed',
    messagingSenderId: '349316653976',
    projectId: 'aspeak-3645f',
    authDomain: 'aspeak-3645f.firebaseapp.com',
    storageBucket: 'aspeak-3645f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPzk9K1V9XOMEQ1P_4b0M36CbPLgzIwA',
    appId: '1:349316653976:android:f0dd858eecdec8532641ed',
    messagingSenderId: '349316653976',
    projectId: 'aspeak-3645f',
    storageBucket: 'aspeak-3645f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAms8VM1-9iwijQ-PatLbO9UQ0nLknhxEg',
    appId: '1:349316653976:ios:4b52f0048f1ff6322641ed',
    messagingSenderId: '349316653976',
    projectId: 'aspeak-3645f',
    storageBucket: 'aspeak-3645f.firebasestorage.app',
    iosBundleId: 'com.example.aspeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAms8VM1-9iwijQ-PatLbO9UQ0nLknhxEg',
    appId: '1:349316653976:ios:4b52f0048f1ff6322641ed',
    messagingSenderId: '349316653976',
    projectId: 'aspeak-3645f',
    storageBucket: 'aspeak-3645f.firebasestorage.app',
    iosBundleId: 'com.example.aspeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdiQ3G8cmHV2tVPMNCqNuMtS2Y3JMgW_4',
    appId: '1:349316653976:web:0366a9e16bf8cc212641ed',
    messagingSenderId: '349316653976',
    projectId: 'aspeak-3645f',
    authDomain: 'aspeak-3645f.firebaseapp.com',
    storageBucket: 'aspeak-3645f.firebasestorage.app',
  );
}
